/**
 * TYPE DEFINITIONS - types/index.ts
 *
 * Purpose: Shared TypeScript types for the application
 *
 * Categories:
 * - User types: User, Session, UserRole
 * - Provider types: Provider, ProviderSummary, ProviderStatus
 * - Category types: Category, CategoryTree
 * - Review types: Review, ReviewSummary
 * - Search types: SearchParams, SearchResult
 * - Location types: Coordinates, Bounds, Location
 * - Analytics types: Event, EventProperties
 *
 * Note: Database types are generated by Prisma
 * These are application-level types for components and API
 */

// ============ User Types ============

export type UserRole = "USER" | "PROVIDER" | "ADMIN";

export interface User {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  role: UserRole;
  providerId?: string;
  createdAt: Date;
}

// ============ Provider Types ============

export type ProviderStatus = "PENDING" | "ACTIVE" | "SUSPENDED";
export type PriceBand = 1 | 2 | 3;

export interface ProviderSummary {
  id: string;
  name: string;
  slug: string;
  photo: string | null;
  category: {
    name: string;
    icon: string | null;
  };
  rating: number | null;
  reviewCount: number;
  priceBand: PriceBand;
  distance?: number;
  isAvailable: boolean;
  isFeatured: boolean;
}

export interface Provider extends ProviderSummary {
  description: string;
  bio: string | null;
  photos: string[];
  categories: Category[];
  services: string[];
  languages: string[];
  schedule: WeeklySchedule;
  contact: ContactInfo;
  location: Location;
  isVerified: boolean;
  status: ProviderStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface ContactInfo {
  phone: string;
  whatsapp?: string;
  email?: string;
  website?: string;
}

export interface Location {
  address: string;
  city: string;
  lat: number;
  lng: number;
  serviceRadius?: number;
}

export interface DaySchedule {
  open: string;
  close: string;
}

export type WeeklySchedule = {
  [key in "sunday" | "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday"]: DaySchedule | null;
};

// ============ Category Types ============

export interface Category {
  id: string;
  name: string;
  nameHe: string;
  slug: string;
  icon: string | null;
  description: string | null;
  parentId: string | null;
  sortOrder: number;
  providerCount?: number;
  children?: Category[];
}

// ============ Review Types ============

export type ReviewStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface Review {
  id: string;
  rating: number;
  text: string;
  photos?: string[];
  user: {
    name: string;
    initial: string;
  };
  createdAt: Date;
  isVerified: boolean;
}

export interface ReviewSummary {
  average: number;
  count: number;
  distribution: Record<1 | 2 | 3 | 4 | 5, number>;
}

// ============ Search Types ============

export interface SearchParams {
  q?: string;
  category?: string;
  lat?: number;
  lng?: number;
  radius?: number;
  price?: string;
  available?: boolean;
  sort?: "distance" | "rating" | "featured";
  page?: number;
  limit?: number;
}

export interface SearchResult {
  providers: ProviderSummary[];
  total: number;
  page: number;
  totalPages: number;
  facets?: {
    categories: { slug: string; count: number }[];
    cities: { name: string; count: number }[];
    priceBands: { band: number; count: number }[];
  };
}

// ============ Location Types ============

export interface Coordinates {
  lat: number;
  lng: number;
}

export interface Bounds {
  ne: Coordinates;
  sw: Coordinates;
}

// ============ Analytics Types ============

export type AnalyticsEventName =
  | "app_open"
  | "search_submit"
  | "results_shown"
  | "map_move"
  | "result_click"
  | "profile_view"
  | "call_click"
  | "whatsapp_click"
  | "navigate_click"
  | "review_submit"
  | "favorite_add"
  | "favorite_remove";

export interface AnalyticsEvent {
  event: AnalyticsEventName;
  properties: Record<string, string | number | boolean>;
  timestamp: number;
  sessionId: string;
}
